### ISSUE TITLE
install from devel fails

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-powerfit#5]
```
Successfully installed scipion-em-chimera-3.0.0 scipion-em-powerfit-3.0.0
Done (2.62 seconds)
Warning: couldn't find Plugin for scipion-em-powerfit
Dirname: None
Traceback (most recent call last):
File "/home/gsharov/soft/scipion3/scipion-app/scipion/__main__.py", line 470, in <module>
main()
File "/home/gsharov/soft/scipion3/scipion-app/scipion/__main__.py", line 293, in main
installPluginMethods()
File "/home/gsharov/soft/scipion3/scipion-app/scipion/install/install_plugin.py", line 216, in installPluginMethods
plugin.installBin({'args': ['-j', numberProcessor]})
File "/home/gsharov/soft/scipion3/scipion-app/scipion/install/plugin_funcs.py", line 166, in installBin
environment.execute()
AttributeError: 'NoneType' object has no attribute 'execute'
Error at main: 'NoneType' object has no attribute 'execute'
```

**Comment by azazellochg** [comment]
oops, just noticed it's unsupported for 3.0
